version: '3.8'

services:
  # Service for the backend application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb+srv://alto:HRlqqTP7ps6SyQyU@cluster0.tmu5ihc.mongodb.net/book-management?retryWrites=true&w=majority&appName=Cluster0
      TEST_MONGODB_URI: mongodb+srv://alto:HRlqqTP7ps6SyQyU@cluster0.tmu5ihc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      SECRET: Imbve5Vrt6VgYMZadm7O2zGYZ2fZgD3p
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm start

  # Service for MongoDB
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
